import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1790686464452 implements MigrationInterface {
    name = 'Init1790686464452'

    public async up(queryRunner: QueryRunner): Promise<void> {
        // Made explicit rather than relying on TypeORM's postgres driver
        // auto-creating this on connection init (it does, but a migration
        // run by a different tool/process shouldn't depend on that).
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
        await queryRunner.query(`CREATE TYPE "public"."courses_category_enum" AS ENUM('IT', 'ENGLISH')`);
        await queryRunner.query(`CREATE TABLE "courses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "title_en" character varying NOT NULL, "title_ru" character varying NOT NULL, "title_uz_latn" character varying NOT NULL, "title_uz_cyrl" character varying NOT NULL, "description_en" text, "description_ru" text, "description_uz_latn" text, "description_uz_cyrl" text, "category" "public"."courses_category_enum" NOT NULL, "price" numeric(12,2), "is_published" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_3f70a487cc718ad8eda4e6d58c9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "key" character varying NOT NULL, "description" character varying NOT NULL, CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_017943867ed5ceef9c03edd974" ON "permissions"  ("key") `);
        await queryRunner.query(`CREATE TYPE "public"."notification_settings_type_enum" AS ENUM('PAYMENT_DUE', 'NEW_ASSIGNMENT', 'GRADE_POSTED', 'CLASS_REMINDER', 'ABSENCE')`);
        await queryRunner.query(`CREATE TABLE "notification_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "type" "public"."notification_settings_type_enum" NOT NULL, "enabled" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_d131abd7996c475ef768d4559ba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ebe50fd4f0ce14b98962eafed4" ON "notification_settings"  ("type") `);
        await queryRunner.query(`CREATE TABLE "telegram_bot_config" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "bot_token" character varying, "bot_username" character varying, "is_connected" boolean NOT NULL DEFAULT false, "last_checked_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_e50c695fd853870d3295a59bfaf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."role_permissions_role_enum" AS ENUM('FULL_ADMIN', 'CEO', 'ADMIN_STAFF', 'TEACHER', 'STUDENT')`);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "role" "public"."role_permissions_role_enum" NOT NULL, "permission_id" uuid NOT NULL, "granted" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_9b6dd376ceeb1c43ae35000fb5b" UNIQUE ("role", "permission_id"), CONSTRAINT "PK_84059017c90bfcb701b8fa42297" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5d5086bd299f773d403574cf1c" ON "role_permissions"  ("role") `);
        await queryRunner.query(`CREATE TABLE "student_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid NOT NULL, "parent_telegram_username" character varying, "parent_chat_id" character varying, "parent_linked" boolean NOT NULL DEFAULT false, "parent_link_token" character varying, "enrollment_date" date, "date_of_birth" date, CONSTRAINT "REL_cef016a0d95e26ae7c0f167ec2" UNIQUE ("user_id"), CONSTRAINT "PK_5ed0a32eeaddfe812fb326177d0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "teacher_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid NOT NULL, "title_en" character varying, "title_ru" character varying, "title_uz_latn" character varying, "title_uz_cyrl" character varying, "bio_en" text, "bio_ru" text, "bio_uz_latn" text, "bio_uz_cyrl" text, "public_photo_url" character varying, "subjects" text, "teaching_languages" text, "is_published" boolean NOT NULL DEFAULT false, CONSTRAINT "REL_b9627de400103265c502c57b56" UNIQUE ("user_id"), CONSTRAINT "PK_fdd17d62015e40674217a407484" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('FULL_ADMIN', 'CEO', 'ADMIN_STAFF', 'TEACHER', 'STUDENT')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "email" character varying NOT NULL, "password_hash" character varying NOT NULL, "role" "public"."users_role_enum" NOT NULL, "first_name" character varying NOT NULL, "last_name" character varying NOT NULL, "phone" character varying, "avatar_url" character varying, "preferred_locale" character varying NOT NULL DEFAULT 'en', "is_active" boolean NOT NULL DEFAULT true, "last_login_at" TIMESTAMP WITH TIME ZONE, "telegram_chat_id" character varying, "telegram_link_token" character varying, CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users"  ("email") `);
        await queryRunner.query(`CREATE TYPE "public"."groups_category_enum" AS ENUM('IT', 'ENGLISH')`);
        await queryRunner.query(`CREATE TABLE "groups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "category" "public"."groups_category_enum" NOT NULL, "teacher_user_id" uuid NOT NULL, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_659d1483316afb28afd3a90646e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "attendance_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "group_id" uuid NOT NULL, "student_user_id" uuid NOT NULL, "date" date NOT NULL, "present" boolean NOT NULL DEFAULT true, "marked_by_user_id" uuid, "marked_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "UQ_3fa5c774b312b9b5f5a59884a84" UNIQUE ("group_id", "student_user_id", "date"), CONSTRAINT "PK_946920332f5bc9efad3f3023b96" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "about_page" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "body_en" text NOT NULL DEFAULT '', "body_ru" text NOT NULL DEFAULT '', "body_uz_latn" text NOT NULL DEFAULT '', "body_uz_cyrl" text NOT NULL DEFAULT '', "updated_by_user_id" uuid, CONSTRAINT "PK_1dc8841661aab05254e3b99b3a2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."news_posts_category_enum" AS ENUM('NEW_GROUP', 'RESULTS', 'SCHEDULE', 'CENTER_NEWS', 'EVENTS')`);
        await queryRunner.query(`CREATE TYPE "public"."news_posts_status_enum" AS ENUM('DRAFT', 'PUBLISHED')`);
        await queryRunner.query(`CREATE TABLE "news_posts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "title_en" character varying NOT NULL, "title_ru" character varying NOT NULL, "title_uz_latn" character varying NOT NULL, "title_uz_cyrl" character varying NOT NULL, "body_en" text NOT NULL, "body_ru" text NOT NULL, "body_uz_latn" text NOT NULL, "body_uz_cyrl" text NOT NULL, "cover_image_file_key" character varying, "category" "public"."news_posts_category_enum" NOT NULL, "status" "public"."news_posts_status_enum" NOT NULL DEFAULT 'DRAFT', "published_at" TIMESTAMP WITH TIME ZONE, "author_user_id" uuid, CONSTRAINT "PK_95a44578e2b4bb7ca42e3ef4de6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."conversations_type_enum" AS ENUM('DIRECT', 'GROUP')`);
        await queryRunner.query(`CREATE TABLE "conversations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "type" "public"."conversations_type_enum" NOT NULL, "linked_group_id" uuid, CONSTRAINT "PK_ee34f4f7ced4ec8681f26bf04ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "conversation_participants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "conversation_id" uuid NOT NULL, "user_id" uuid NOT NULL, "last_read_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_fdcd6405d74e797f10fa8360338" UNIQUE ("conversation_id", "user_id"), CONSTRAINT "PK_61b51428ad9453f5921369fbe94" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "conversation_id" uuid NOT NULL, "sender_id" uuid NOT NULL, "text" text, "attachment_file_key" character varying, "sent_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."requests_source_enum" AS ENUM('WEBSITE', 'MANUAL')`);
        await queryRunner.query(`CREATE TYPE "public"."requests_status_enum" AS ENUM('NEW', 'TRIAL_SCHEDULED', 'TRIAL_DONE', 'ACTIVE', 'DECLINED')`);
        await queryRunner.query(`CREATE TABLE "requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "full_name" character varying NOT NULL, "phone" character varying NOT NULL, "email" character varying, "source" "public"."requests_source_enum" NOT NULL, "status" "public"."requests_status_enum" NOT NULL DEFAULT 'NEW', "decline_reason" character varying, "trial_lesson_at" TIMESTAMP WITH TIME ZONE, "message" text, "notes" text, "course_interest_id" uuid, "converted_student_user_id" uuid, "assigned_group_id" uuid, CONSTRAINT "PK_0428f484e96f9e6a55955f29b5f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "group_memberships" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "group_id" uuid NOT NULL, "student_user_id" uuid NOT NULL, "joined_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_9058c84f1b71817a8a8d2dad7b6" UNIQUE ("group_id", "student_user_id"), CONSTRAINT "PK_4a04ebe9f25ad41f45b2c0ca4b5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notification_logs_recipient_type_enum" AS ENUM('USER', 'PARENT')`);
        await queryRunner.query(`CREATE TYPE "public"."notification_logs_type_enum" AS ENUM('PAYMENT_DUE', 'NEW_ASSIGNMENT', 'GRADE_POSTED', 'CLASS_REMINDER', 'ABSENCE')`);
        await queryRunner.query(`CREATE TYPE "public"."notification_logs_status_enum" AS ENUM('QUEUED', 'SENT', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "notification_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "recipient_type" "public"."notification_logs_recipient_type_enum" NOT NULL, "recipient_user_id" uuid, "recipient_chat_id" character varying, "type" "public"."notification_logs_type_enum" NOT NULL, "message" text NOT NULL, "status" "public"."notification_logs_status_enum" NOT NULL DEFAULT 'QUEUED', "sent_at" TIMESTAMP WITH TIME ZONE, "error_message" text, CONSTRAINT "PK_19c524e644cdeaebfcffc284871" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payment_cycles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "student_user_id" uuid NOT NULL, "cycle_number" integer NOT NULL, "lessons_count" integer NOT NULL DEFAULT '12', "amount" numeric(12,2) NOT NULL, "paid_at" TIMESTAMP WITH TIME ZONE NOT NULL, "recorded_by_user_id" uuid, "notes" text, CONSTRAINT "PK_b51b5d999be0a96ed09f7a7bae7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."student_payment_statuses_status_enum" AS ENUM('CURRENT', 'OUTSTANDING', 'OVERDUE')`);
        await queryRunner.query(`CREATE TABLE "student_payment_statuses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "student_user_id" uuid NOT NULL, "status" "public"."student_payment_statuses_status_enum" NOT NULL DEFAULT 'CURRENT', "set_by_user_id" uuid, "set_at" TIMESTAMP WITH TIME ZONE, "note" text, CONSTRAINT "REL_035f3774173b74d5a27c3c72ff" UNIQUE ("student_user_id"), CONSTRAINT "PK_d9b4dc16d36bcec58cb3dac2852" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."report_exports_type_enum" AS ENUM('REVENUE', 'OUTSTANDING_PAYMENTS', 'ENROLLMENT', 'ATTENDANCE_RATES', 'TEACHER_STUDENT_PERFORMANCE')`);
        await queryRunner.query(`CREATE TYPE "public"."report_exports_status_enum" AS ENUM('PENDING', 'READY', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "report_exports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "type" "public"."report_exports_type_enum" NOT NULL, "params" text NOT NULL, "requested_by_user_id" uuid, "status" "public"."report_exports_status_enum" NOT NULL DEFAULT 'PENDING', "generated_at" TIMESTAMP WITH TIME ZONE, "file_key" character varying, "filename" character varying, "size_bytes" bigint, "error_message" text, CONSTRAINT "PK_831f34e4d6c47ec2bb42a614465" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tasks_type_enum" AS ENUM('FILE', 'TEXT', 'MCQ', 'AUTO_TEST')`);
        await queryRunner.query(`CREATE TABLE "tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "group_id" uuid NOT NULL, "teacher_user_id" uuid NOT NULL, "title_en" character varying NOT NULL, "title_ru" character varying NOT NULL, "title_uz_latn" character varying NOT NULL, "title_uz_cyrl" character varying NOT NULL, "description_en" text, "description_ru" text, "description_uz_latn" text, "description_uz_cyrl" text, "type" "public"."tasks_type_enum" NOT NULL, "attachment_file_key" character varying, CONSTRAINT "PK_8d12ff38fcc62aaba2cab748772" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."submissions_status_enum" AS ENUM('PENDING', 'GRADED')`);
        await queryRunner.query(`CREATE TABLE "submissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "task_id" uuid NOT NULL, "student_user_id" uuid NOT NULL, "text_answer" text, "file_key" character varying, "answers" text, "correct_count" integer, "total_count" integer, "status" "public"."submissions_status_enum" NOT NULL DEFAULT 'PENDING', "graded_by_user_id" uuid, "graded_at" TIMESTAMP WITH TIME ZONE, "comment" text, "submitted_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "UQ_a3813fc50b7fcab8fb83c2a499f" UNIQUE ("task_id", "student_user_id"), CONSTRAINT "PK_10b3be95b8b2fb1e482e07d706b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."schedule_slots_day_of_week_enum" AS ENUM('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')`);
        await queryRunner.query(`CREATE TABLE "schedule_slots" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "group_id" uuid NOT NULL, "day_of_week" "public"."schedule_slots_day_of_week_enum" NOT NULL, "start_time" TIME NOT NULL, "end_time" TIME NOT NULL, "room" character varying, CONSTRAINT "PK_11236e5138891d4dd3cc8a8b564" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "task_questions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "task_id" uuid NOT NULL, "sort_order" integer NOT NULL DEFAULT '0', "question_text" text NOT NULL, "options" text NOT NULL, "correct_option_index" integer NOT NULL, "hint" text, CONSTRAINT "PK_a07261605d16a4246e2de4e41ae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_profiles" ADD CONSTRAINT "FK_cef016a0d95e26ae7c0f167ec28" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teacher_profiles" ADD CONSTRAINT "FK_b9627de400103265c502c57b56b" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_0789f536efb51670cfd4b78e659" FOREIGN KEY ("teacher_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "FK_838494df398645bdf3223d49075" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "FK_0dadf21d987611393bd9c3d0705" FOREIGN KEY ("student_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "FK_f409e4840b0aa6c3331df0ab11f" FOREIGN KEY ("marked_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "about_page" ADD CONSTRAINT "FK_72ae2031a88250ba16a2bac9d39" FOREIGN KEY ("updated_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "news_posts" ADD CONSTRAINT "FK_ecd95df7ccc94dca4e00b179ac3" FOREIGN KEY ("author_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_27a34d630ce335119979b86398f" FOREIGN KEY ("linked_group_id") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" ADD CONSTRAINT "FK_1559e8a16b828f2e836a2312800" FOREIGN KEY ("conversation_id") REFERENCES "conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" ADD CONSTRAINT "FK_377d4041a495b81ee1a85ae026f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_3bc55a7c3f9ed54b520bb5cfe23" FOREIGN KEY ("conversation_id") REFERENCES "conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_22133395bd13b970ccd0c34ab22" FOREIGN KEY ("sender_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "requests" ADD CONSTRAINT "FK_0e3075bd68076465a90dde7df30" FOREIGN KEY ("course_interest_id") REFERENCES "courses"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "requests" ADD CONSTRAINT "FK_3bee60f4abf2fbd66cca57d1362" FOREIGN KEY ("converted_student_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "requests" ADD CONSTRAINT "FK_d58c5373af8cdc865b02918a857" FOREIGN KEY ("assigned_group_id") REFERENCES "groups"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_memberships" ADD CONSTRAINT "FK_cad344fe877fcee0ac7e065ed05" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_memberships" ADD CONSTRAINT "FK_2ec68a69a958ac3d7256765737e" FOREIGN KEY ("student_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_logs" ADD CONSTRAINT "FK_4a106b58808f39fff82df34e55c" FOREIGN KEY ("recipient_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_cycles" ADD CONSTRAINT "FK_4ebadc29b118804eacdb50314b4" FOREIGN KEY ("student_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_cycles" ADD CONSTRAINT "FK_11eb082ad155dfe0adee68f1886" FOREIGN KEY ("recorded_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_payment_statuses" ADD CONSTRAINT "FK_035f3774173b74d5a27c3c72ff7" FOREIGN KEY ("student_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_payment_statuses" ADD CONSTRAINT "FK_059cd1fd531c3bef86d1dc02651" FOREIGN KEY ("set_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_exports" ADD CONSTRAINT "FK_e608ae76f116c4971f68be12bcb" FOREIGN KEY ("requested_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_438e3c81c9f4209c13483661157" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_660c1f91bb6c7287d573808aebf" FOREIGN KEY ("teacher_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD CONSTRAINT "FK_777fd1f8e4c40e606e1ce24974a" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD CONSTRAINT "FK_6ef3b6066007bbbba84342483ee" FOREIGN KEY ("student_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD CONSTRAINT "FK_4f2128de95b9741a1044393174d" FOREIGN KEY ("graded_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_slots" ADD CONSTRAINT "FK_0c1a82be05cd36acae48396a5c5" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_questions" ADD CONSTRAINT "FK_7aee31280bee244443f0bb216be" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "task_questions" DROP CONSTRAINT "FK_7aee31280bee244443f0bb216be"`);
        await queryRunner.query(`ALTER TABLE "schedule_slots" DROP CONSTRAINT "FK_0c1a82be05cd36acae48396a5c5"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP CONSTRAINT "FK_4f2128de95b9741a1044393174d"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP CONSTRAINT "FK_6ef3b6066007bbbba84342483ee"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP CONSTRAINT "FK_777fd1f8e4c40e606e1ce24974a"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_660c1f91bb6c7287d573808aebf"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_438e3c81c9f4209c13483661157"`);
        await queryRunner.query(`ALTER TABLE "report_exports" DROP CONSTRAINT "FK_e608ae76f116c4971f68be12bcb"`);
        await queryRunner.query(`ALTER TABLE "student_payment_statuses" DROP CONSTRAINT "FK_059cd1fd531c3bef86d1dc02651"`);
        await queryRunner.query(`ALTER TABLE "student_payment_statuses" DROP CONSTRAINT "FK_035f3774173b74d5a27c3c72ff7"`);
        await queryRunner.query(`ALTER TABLE "payment_cycles" DROP CONSTRAINT "FK_11eb082ad155dfe0adee68f1886"`);
        await queryRunner.query(`ALTER TABLE "payment_cycles" DROP CONSTRAINT "FK_4ebadc29b118804eacdb50314b4"`);
        await queryRunner.query(`ALTER TABLE "notification_logs" DROP CONSTRAINT "FK_4a106b58808f39fff82df34e55c"`);
        await queryRunner.query(`ALTER TABLE "group_memberships" DROP CONSTRAINT "FK_2ec68a69a958ac3d7256765737e"`);
        await queryRunner.query(`ALTER TABLE "group_memberships" DROP CONSTRAINT "FK_cad344fe877fcee0ac7e065ed05"`);
        await queryRunner.query(`ALTER TABLE "requests" DROP CONSTRAINT "FK_d58c5373af8cdc865b02918a857"`);
        await queryRunner.query(`ALTER TABLE "requests" DROP CONSTRAINT "FK_3bee60f4abf2fbd66cca57d1362"`);
        await queryRunner.query(`ALTER TABLE "requests" DROP CONSTRAINT "FK_0e3075bd68076465a90dde7df30"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_22133395bd13b970ccd0c34ab22"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_3bc55a7c3f9ed54b520bb5cfe23"`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" DROP CONSTRAINT "FK_377d4041a495b81ee1a85ae026f"`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" DROP CONSTRAINT "FK_1559e8a16b828f2e836a2312800"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_27a34d630ce335119979b86398f"`);
        await queryRunner.query(`ALTER TABLE "news_posts" DROP CONSTRAINT "FK_ecd95df7ccc94dca4e00b179ac3"`);
        await queryRunner.query(`ALTER TABLE "about_page" DROP CONSTRAINT "FK_72ae2031a88250ba16a2bac9d39"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "FK_f409e4840b0aa6c3331df0ab11f"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "FK_0dadf21d987611393bd9c3d0705"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "FK_838494df398645bdf3223d49075"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_0789f536efb51670cfd4b78e659"`);
        await queryRunner.query(`ALTER TABLE "teacher_profiles" DROP CONSTRAINT "FK_b9627de400103265c502c57b56b"`);
        await queryRunner.query(`ALTER TABLE "student_profiles" DROP CONSTRAINT "FK_cef016a0d95e26ae7c0f167ec28"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`DROP TABLE "task_questions"`);
        await queryRunner.query(`DROP TABLE "schedule_slots"`);
        await queryRunner.query(`DROP TYPE "public"."schedule_slots_day_of_week_enum"`);
        await queryRunner.query(`DROP TABLE "submissions"`);
        await queryRunner.query(`DROP TYPE "public"."submissions_status_enum"`);
        await queryRunner.query(`DROP TABLE "tasks"`);
        await queryRunner.query(`DROP TYPE "public"."tasks_type_enum"`);
        await queryRunner.query(`DROP TABLE "report_exports"`);
        await queryRunner.query(`DROP TYPE "public"."report_exports_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."report_exports_type_enum"`);
        await queryRunner.query(`DROP TABLE "student_payment_statuses"`);
        await queryRunner.query(`DROP TYPE "public"."student_payment_statuses_status_enum"`);
        await queryRunner.query(`DROP TABLE "payment_cycles"`);
        await queryRunner.query(`DROP TABLE "notification_logs"`);
        await queryRunner.query(`DROP TYPE "public"."notification_logs_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notification_logs_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notification_logs_recipient_type_enum"`);
        await queryRunner.query(`DROP TABLE "group_memberships"`);
        await queryRunner.query(`DROP TABLE "requests"`);
        await queryRunner.query(`DROP TYPE "public"."requests_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."requests_source_enum"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP TABLE "conversation_participants"`);
        await queryRunner.query(`DROP TABLE "conversations"`);
        await queryRunner.query(`DROP TYPE "public"."conversations_type_enum"`);
        await queryRunner.query(`DROP TABLE "news_posts"`);
        await queryRunner.query(`DROP TYPE "public"."news_posts_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."news_posts_category_enum"`);
        await queryRunner.query(`DROP TABLE "about_page"`);
        await queryRunner.query(`DROP TABLE "attendance_records"`);
        await queryRunner.query(`DROP TABLE "groups"`);
        await queryRunner.query(`DROP TYPE "public"."groups_category_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "teacher_profiles"`);
        await queryRunner.query(`DROP TABLE "student_profiles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5d5086bd299f773d403574cf1c"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP TYPE "public"."role_permissions_role_enum"`);
        await queryRunner.query(`DROP TABLE "telegram_bot_config"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ebe50fd4f0ce14b98962eafed4"`);
        await queryRunner.query(`DROP TABLE "notification_settings"`);
        await queryRunner.query(`DROP TYPE "public"."notification_settings_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_017943867ed5ceef9c03edd974"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP TABLE "courses"`);
        await queryRunner.query(`DROP TYPE "public"."courses_category_enum"`);
    }

}
